// Pet data
export const pets = [
  {
    id: 11,
    name: "AvaTar",
    age: 1,
    type: "dog",
    breed: "Beagle",
    description: "Curious and playful, has a great sense of smell.",
    image: "./images/avatar.jpg",
  },
  {
    id: 1,
    name: "Buddy",
    age: 3,
    type: "dog",
    breed: "Golden Retriever",
    description: "Friendly and energetic, loves to play fetch.",
    image: "./images/pet1.png",
  },
  {
    id: 2,
    name: "Whiskers",
    age: 2,
    type: "cat",
    breed: "Siamese",
    description: "Curious and vocal, enjoys lounging in sunny spots.",
    image: "./images/pet2.png",
  },
  {
    id: 3,
    name: "Rex",
    age: 5,
    type: "dog",
    breed: "German Shepherd",
    description: "Loyal and protective, great with families.",
    image: "./images/rex.jpg",
  },
  {
    id: 4,
    name: "Mittens",
    age: 1,
    type: "cat",
    breed: "Maine Coon",
    description: "Playful and affectionate, loves to be groomed.",
    image: "./images/mittens.png",
  },
  {
    id: 5,
    name: "Fluffy",
    age: 4,
    type: "cat",
    breed: "Persian",
    description: "Calm and gentle, enjoys a quiet environment.",
    image: "./images/pet5.jpg",
  },
  {
    id: 6,
    name: "Max",
    age: 6,
    type: "dog",
    breed: "Labrador Retriever",
    description: "Outgoing and friendly, great with children.",
    image: "/images/max.jpg",
  },
  {
    id: 7,
    name: "Tammy",
    age: 3,
    type: "other",
    breed: "Syrian Hamster",
    description: "Active at night, loves running on his wheel.",
    image: "./images/No Image Available.png",
  },
  {
    id: 8,
    name: "Polly",
    age: 2,
    type: "other",
    breed: "African Grey Parrot",
    description: "Intelligent and talkative, can mimic human speech.",
    image: "./images/No Image Available.png",
  },
  {
    id: 9,
    name: "Luna",
    age: 1,
    type: "cat",
    breed: "Husky",
    description: "Energetic and friendly, loves cold weather.",
    image: "./images/luna.jpg",
  },
  {
    id: 10,
    name: "Oliver",
    age: 3,
    type: "cat",
    breed: "British Shorthair",
    description: "Calm and easygoing, enjoys lounging around.",
    image: "./images/No Image Available.png",
  },
  {
    id: 12,
    name: "Nemo",
    age: 1,
    type: "other",
    breed: "Clownfish",
    description: "Vibrant and active, perfect for a saltwater aquarium.",
    image: "./images/No Image Available.png",
  },
  {
    id: 13,
    name: "Daisy",
    age: 5,
    type: "dog",
    breed: "Dachshund",
    description: "Clever and stubborn, loves to burrow in blankets.",
    image: "./images/daisy.jpg",
  },
  {
    id: 14,
    name: "Simba",
    age: 2,
    type: "cat",
    breed: "Orange Tabby",
    description: "Adventurous and bold, loves to explore.",
    image: "./images/No Image Available.png",
  },
  {
    id: 15,
    name: "Rocky",
    age: 4,
    type: "dog",
    breed: "Boxer",
    description: "Playful and patient, great with other pets.",
    image: "./images/No Image Available.png",
  },
  {
    id: 16,
    name: "Coco",
    age: 1,
    type: "other",
    breed: "Holland Lop Rabbit",
    description: "Gentle and sociable, enjoys being petted.",
    image: "./images/No Image Available.png",
  },
  {
    id: 17,
    name: "Milo",
    age: 3,
    type: "cat",
    breed: "Scottish Fold",
    description: "Sweet-tempered and quiet, loves to cuddle.",
    image: "./images/pet4.png",
  },
  {
    id: 18,
    name: "Bella",
    age: 6,
    type: "dog",
    breed: "Poodle",
    description: "Intelligent and elegant, hypoallergenic coat.",
    image: "./images/No Image Available.png",
  },
  {
    id: 19,
    name: "Kiwi",
    age: 2,
    type: "other",
    breed: "Green Cheek Conure",
    description: "Playful and affectionate, loves to be handled.",
    image: "./images/No Image Available.png",
  },
  {
    id: 20,
    name: "Oreo",
    age: 1,
    type: "dog",
    breed: "Tuxedo",
    description: "Energetic and mischievous, loves to play.",
    image: "./images/oreo.jpg",
  },
  {
    id: 21,
    name: "Rusty",
    age: 3,
    type: "dog",
    breed: "Australian Shepherd",
    description: "Highly intelligent and active, needs lots of exercise.",
    image: "./images/rusty.jpg",
  },
  {
    id: 22,
    name: "Pepper",
    age: 2,
    type: "other",
    breed: "Guinea Pig",
    description: "Social and gentle, enjoys vegetables and hay.",
    image: "./images/No Image Available.png",
  },
  {
    id: 23,
    name: "Sasha",
    age: 4,
    type: "cat",
    breed: "Russian Blue",
    description: "Shy at first, but very affectionate once comfortable.",
    image: "./images/No Image Available.png",
  },
  {
    id: 24,
    name: "Bruno",
    age: 5,
    type: "dog",
    breed: "Rottweiler",
    description: "Confident and courageous, excellent guard dog.",
    image: "./images/No Image Available.png",
  },
  {
    id: 25,
    name: "Snappie",
    age: 4,
    type: "other",
    breed: "Californian Breed",
    description: "creative, tech-savy and kind",
    image: "./images/snappie.jpg",
  },
  {
    id: 26,
    name: "Ziggy",
    age: 3,
    type: "other",
    breed: "Bearded Dragon",
    description: "Docile and easy to care for, enjoys basking under heat lamps.",
    image: "./images/No Image Available.png",
  },
];
